spring:
  application:
    name: bookshop
  datasource:
    url: jdbc:postgresql://localhost:5432/shopbook
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
